initial_pos_list: [[-0.24, 0.25, -0.12], [-0.24, -0.01, -0.12], [-0.24, -0.32, -0.12], [-0.22, 0.25, -0.41], [-0.24, -0.01, -0.41], [-0.24, -0.32, -0.41]]
initial_rot_list: [[0,0,0], [0,0,0], [0,0,0], [0,0,0], [0,0,0], [0,0,0]]
initial_quat_list: [[0,0,0,1], [0,0,0,1], [0,0,0,1], [0,0,0,1], [0,0,0,1], [0,0,0,1]]
dimensions: [[0.38, 0.23, 0.18],[0.38, 0.27, 0.18],[0.38, 0.23, 0.18], [0.38, 0.23, 0.20],[0.38, 0.27, 0.20],[0.38, 0.23, 0.20]]
frame_id_list: [kiva_pod_base, kiva_pod_base, kiva_pod_base, kiva_pod_base, kiva_pod_base, kiva_pod_base]
prefixes: [bin_g, bin_h, bin_i, bin_j, bin_k, bin_l]
camera_directions: [x, x, x, x, x, x]
